@startuml
skin rose
title sequence diagram
actor user
box Methods #LightBlue
    participant deposit
    participant withdraw
end box
box Variables #LightGreen
    collections bitcoins
end box

== Deposit bitcoins ==

user -> deposit
deposit -> bitcoins : add bitcoins to the wallet

== Withdraw bitcoins ==

user -> withdraw
withdraw -> bitcoins : withdraw bitcoins from the wallet

@enduml
